"""
Entity mapping functionality for GCGAAP.

Provides the ability to map GnuCash accounts to logical entities (e.g., personal,
various businesses) using the entity_account_map.json file generated by the
entity account mapper tool.
"""

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class EntityDefinition:
    """
    Definition of a logical entity within the GnuCash book.
    
    Attributes:
        key: Unique identifier for this entity (e.g., "personal", "alpha_llc").
        label: Human-readable display name.
        type: Entity type - "individual", "business", or "structural".
    """
    
    key: str
    label: str
    type: str  # "individual", "business", or "structural"
    
    def __post_init__(self):
        """Validate entity type."""
        if self.type not in ("individual", "business", "structural"):
            logger.warning(
                f"Entity '{self.key}' has unexpected type '{self.type}'. "
                f"Expected 'individual', 'business', or 'structural'."
            )


@dataclass
class EntityMap:
    """
    Maps GnuCash accounts to logical entities.
    
    Loads mapping data from entity_account_map.json generated by the
    entity account mapper tool.
    
    Attributes:
        entities: Dictionary of entity definitions keyed by entity key.
        account_entities: Dictionary mapping account GUID to entity key.
        default_entity: Default entity for unmapped accounts (usually "unassigned").
    """
    
    entities: dict[str, EntityDefinition] = field(default_factory=dict)
    account_entities: dict[str, str] = field(default_factory=dict)
    default_entity: str = "unassigned"
    
    def __post_init__(self):
        """Ensure default entity exists."""
        if self.default_entity not in self.entities:
            self.entities[self.default_entity] = EntityDefinition(
                key=self.default_entity,
                label="Unassigned",
                type="individual"
            )
    
    @classmethod
    def load(cls, path: Path) -> "EntityMap":
        """
        Load entity map from entity_account_map.json file.
        
        Args:
            path: Path to the entity_account_map.json file.
            
        Returns:
            EntityMap instance loaded from the file.
            
        Raises:
            FileNotFoundError: If the file does not exist.
            json.JSONDecodeError: If the file is not valid JSON.
            KeyError: If required fields are missing.
        """
        logger.info(f"Loading entity map from {path}")
        
        if not path.exists():
            logger.warning(f"Entity map file not found: {path}")
            logger.warning("Starting with empty entity map")
            return cls()
        
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        summary = data.get("summary", {})
        entities_data = data.get("entities", {})
        entity_labels = summary.get("entity_labels", {})
        
        # Build entity definitions
        entities = {}
        for entity_key in entities_data.keys():
            label = entity_labels.get(entity_key, entity_key.replace("_", " ").title())
            # Determine type based on entity key naming convention
            if entity_key in ("personal", "unassigned"):
                entity_type = "individual"
            elif entity_key == "placeholder_only_acct":
                entity_type = "structural"
            else:
                entity_type = "business"
            
            entities[entity_key] = EntityDefinition(
                key=entity_key,
                label=label,
                type=entity_type
            )
        
        # Build account GUID to entity mapping
        account_entities = {}
        for entity_key, accounts in entities_data.items():
            for account in accounts:
                guid = account["guid"]
                account_entities[guid] = entity_key
        
        # Determine default entity
        default_entity = "unassigned" if "unassigned" in entities else list(entities.keys())[0] if entities else "unassigned"
        
        entity_map = cls(
            entities=entities,
            account_entities=account_entities,
            default_entity=default_entity
        )
        
        logger.info(
            f"Loaded {len(entities)} entities with "
            f"{len(account_entities)} account mappings"
        )
        
        return entity_map
    
    def resolve_entity_for_account(
        self, 
        guid: str, 
        full_name: str
    ) -> str:
        """
        Resolve the entity key for a given account.
        
        Looks up the account GUID in the mapping. If not found, returns default_entity.
        
        Args:
            guid: The account GUID.
            full_name: The account's full name (not used in new mapping, but kept for API compatibility).
            
        Returns:
            The entity key (always returns a value, defaults to self.default_entity).
        """
        # Check GUID mapping
        if guid in self.account_entities:
            return self.account_entities[guid]
        
        # No match found - return default entity
        logger.debug(
            f"Account '{full_name}' ({guid}) not found in mapping, "
            f"using default entity '{self.default_entity}'"
        )
        return self.default_entity
    
    def is_explicitly_mapped(
        self,
        guid: str,
        full_name: str
    ) -> bool:
        """
        Check if an account has explicit mapping (not using default).
        
        Args:
            guid: The account GUID.
            full_name: The account's full name (not used, kept for API compatibility).
            
        Returns:
            True if account has GUID mapping, False if using default.
        """
        return guid in self.account_entities
